---
- name: Initial Config
  gather_facts: false
  hosts: all
  connection: local
  become: true

  tasks:
    - name: Update APT
      apt:
        update_cache: true

    - name: Upgrade APT
      apt:
        upgrade: yes

    - name: Installing some Packages
      apt:
        name:
          - iputils-ping
          - bsdmainutils
          - bind9-dnsutils
          - curl
          - vim
          - screen
          - lynx
          - htop
          - mc
          - taskwarrior
        state: present
