---
- name: Initial Config
  gather_facts: false
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: "APT: update and upgrade"
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: yes

    - name: Installing some Packages
      ansible.builtin.apt:
        name:
          - iputils-ping
          - bsdmainutils
          - bind9-dnsutils
          - curl
          - vim
          - screen
          - lynx
          - htop
          - mc
          - taskwarrior
          - i3-wm
          - i3blocks
          - i3lock
          - i3status
        state: present

    - name: Install VIM pathogen
      shell: |
        mkdir -p ~/.vim/autoload ~/.vim/bundle ~/src && \
        curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
      
    - name: Clone VIM Plugins
      git:
        repo: "{{ item }}"
        dest: "~/.vim/bundle/{{ item | basename }}"
      loop:
        - https://github.com/scrooloose/nerdtree
        - https://github.com/bling/vim-airline
        - https://github.com/fatih/vim-go
        - https://github.com/rip-rip/clang_complete
        - https://github.com/davidhalter/jedi-vim

    - name: Clone Mulatinho Repository
      git:
        repo: https://github.com/mulatinho/mulatinho
        dest: ~/src/
    
    - name: "Copy configs for i3wm, i3status, and .vimrc"
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: yes
      loop:
        - { src: ~/src/mulatinho/config/i3/config, dest: ~/.config/i3/config }
        - { src: ~/src/mulatinho/config/i3status/config, dest: ~/.config/i3status/config }
        - { src: ~/src/mulatinho/.vimrc, dest: ~/.vimrc }