---
- name: Initial Config
  gather_facts: true
  hosts: localhost
  connection: local

  tasks:
    - name: "NetBSD Initilization"
      include_tasks: netbsd.yaml 
      when: ansible_os_family == "NetBSD"

    - name: "Linux Initialization"
      include_tasks: linux.yaml 
      when: ansible_os_family != "NetBSD"

    - name: Creating some directories
      shell: |
        mkdir -p ~/.config/i3 ~/.config/i3status ~/.vim/autoload ~/.vim/bundle/ ~/src

    - name: Install VIM pathogen
      shell: |
        curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
      
    - name: Clone VIM Plugins
      git:
        repo: "{{ item }}"
        dest: "~/.vim/bundle/{{ item | basename }}"
      loop:
        - https://github.com/scrooloose/nerdtree
        - https://github.com/bling/vim-airline
        - https://github.com/fatih/vim-go
        - https://github.com/davidhalter/jedi-vim
        - https://github.com/vim-scripts/c.vim

    - name: Clone Mulatinho Repository
      git:
        repo: https://github.com/mulatinho/mulatinho
        dest: "~/src/mulatinho"
    
    - name: "Copy configs for i3wm, i3status, and .vimrc"
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: yes
      loop:
        - { src: "~/src/mulatinho/.config/i3/config", dest: "~/.config/i3/config" }
        - { src: "~/src/mulatinho/.config/i3status/config", dest: "~/.config/i3status/config" }
        - { src: "~/src/mulatinho/.vimrc", dest: "~/.vimrc" }